sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
script:
  - (cd evaluation_script && python -m unittest -v conll18_ud_eval)
  - (cd evaluation_script && python conll18_ud_eval.py -v tests/gold.conllu tests/sys1.conllu | diff -s tests/sys1-expected.results -)
  - (cd evaluation_script && python conll18_ud_eval.py -v tests/gold.conllu tests/sys2.conllu | diff -s tests/sys2-expected.results -)
  - (cd evaluation_script && python conll18_ud_eval.py -v tests/gold.conllu tests/sys-space.conllu | diff -s tests/sys-space-expected.results -)
  - (cd evaluation_script && python conll18_ud_eval.py -v tests/case-gold.conllu tests/case-sys.conllu | diff -s tests/case-expected.results -)
  - (cd evaluation_script && python conll18_ud_eval.py -c tests/func-gold.conllu tests/func-sys.conllu | diff -s tests/func-expected.counts -)

